// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA92azeaGdrFgYdaJ8M8KqKWj4iCzKuDHI',
    appId: '1:183304837148:web:d1ac1465df7609984f67d9',
    messagingSenderId: '183304837148',
    projectId: 'ecommerce-bitirme-40020',
    authDomain: 'ecommerce-bitirme-40020.firebaseapp.com',
    storageBucket: 'ecommerce-bitirme-40020.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJccvULX11P639b63tgUdyQOlr3tzduoM',
    appId: '1:183304837148:android:0a066fddd03750834f67d9',
    messagingSenderId: '183304837148',
    projectId: 'ecommerce-bitirme-40020',
    storageBucket: 'ecommerce-bitirme-40020.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvELAeBVPIUyPWYW6qxB2WvWSh6gcAxng',
    appId: '1:183304837148:ios:85b2d1785e5a3a8d4f67d9',
    messagingSenderId: '183304837148',
    projectId: 'ecommerce-bitirme-40020',
    storageBucket: 'ecommerce-bitirme-40020.appspot.com',
    iosClientId: '183304837148-mif8lffe3aih1h07ccojm67cq8ogir9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvELAeBVPIUyPWYW6qxB2WvWSh6gcAxng',
    appId: '1:183304837148:ios:85b2d1785e5a3a8d4f67d9',
    messagingSenderId: '183304837148',
    projectId: 'ecommerce-bitirme-40020',
    storageBucket: 'ecommerce-bitirme-40020.appspot.com',
    iosClientId: '183304837148-mif8lffe3aih1h07ccojm67cq8ogir9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA92azeaGdrFgYdaJ8M8KqKWj4iCzKuDHI',
    appId: '1:183304837148:web:85f8acfed2f121514f67d9',
    messagingSenderId: '183304837148',
    projectId: 'ecommerce-bitirme-40020',
    authDomain: 'ecommerce-bitirme-40020.firebaseapp.com',
    storageBucket: 'ecommerce-bitirme-40020.appspot.com',
  );

}